module.exports = { A: 
   [ { categories: { one: [ 'A' ] },
       name: 'Post 1',
       content: 'Post 1',
       key: 'post-1.md',
       tags: [ 'A' ] },
     { categories: { one: [ 'A' ], two: [ 'B', 'C' ] },
       name: 'Post 2',
       content: 'Post 2',
       key: 'post-2.md',
       tags: [ 'A', 'B', 'C' ] },
     { categories: { one: [ 'A' ], two: [ 'B', 'C' ] },
       name: 'Post 2',
       content: 'Post 2',
       key: 'post-2.md',
       tags: [ 'A', 'B', 'C' ] } ],
  B: 
   [ { categories: { one: [ 'A' ], two: [ 'B', 'C' ] },
       name: 'Post 2',
       content: 'Post 2',
       key: 'post-2.md',
       tags: [ 'A', 'B', 'C' ] },
     { categories: { one: [ 'B' ], two: [ 'C', 'D' ] },
       name: 'Post 3',
       content: 'Post 3',
       key: 'post-3.md',
       tags: [ 'B', 'C', 'D' ] },
     { categories: { one: [ 'A' ], two: [ 'B', 'C' ] },
       name: 'Post 2',
       content: 'Post 2',
       key: 'post-2.md',
       tags: [ 'A', 'B', 'C' ] },
     { categories: { one: [ 'B' ], two: [ 'C', 'D' ] },
       name: 'Post 3',
       content: 'Post 3',
       key: 'post-3.md',
       tags: [ 'B', 'C', 'D' ] },
     { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] },
     { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] } ],
  C: 
   [ { categories: { one: [ 'A' ], two: [ 'B', 'C' ] },
       name: 'Post 2',
       content: 'Post 2',
       key: 'post-2.md',
       tags: [ 'A', 'B', 'C' ] },
     { categories: { one: [ 'B' ], two: [ 'C', 'D' ] },
       name: 'Post 3',
       content: 'Post 3',
       key: 'post-3.md',
       tags: [ 'B', 'C', 'D' ] },
     { categories: { one: [ 'A' ], two: [ 'B', 'C' ] },
       name: 'Post 2',
       content: 'Post 2',
       key: 'post-2.md',
       tags: [ 'A', 'B', 'C' ] },
     { categories: { one: [ 'B' ], two: [ 'C', 'D' ] },
       name: 'Post 3',
       content: 'Post 3',
       key: 'post-3.md',
       tags: [ 'B', 'C', 'D' ] },
     { categories: { four: [ 'C', 'F' ] },
       name: 'Post 5',
       content: 'Post 5',
       key: 'post-5.md',
       tags: [ 'C', 'F' ] } ],
  D: 
   [ { categories: { one: [ 'B' ], two: [ 'C', 'D' ] },
       name: 'Post 3',
       content: 'Post 3',
       key: 'post-3.md',
       tags: [ 'B', 'C', 'D' ] },
     { categories: { one: [ 'B' ], two: [ 'C', 'D' ] },
       name: 'Post 3',
       content: 'Post 3',
       key: 'post-3.md',
       tags: [ 'B', 'C', 'D' ] } ],
  E: 
   [ { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] },
     { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] } ],
  F: 
   [ { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] },
     { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] },
     { categories: { four: [ 'C', 'F' ] },
       name: 'Post 5',
       content: 'Post 5',
       key: 'post-5.md',
       tags: [ 'C', 'F' ] },
     { categories: { four: [ 'F', 'G' ] },
       name: 'Post 6',
       content: 'Post 6',
       key: 'post-6.md',
       tags: [ 'F', 'G' ] } ],
  G: 
   [ { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] },
     { categories: { three: [ 'B' ], four: [ 'E', 'F', 'G' ] },
       name: 'Post 4',
       content: 'Post 4',
       key: 'post-4.md',
       tags: [ 'B', 'E', 'F', 'G' ] },
     { categories: { four: [ 'F', 'G' ] },
       name: 'Post 6',
       content: 'Post 6',
       key: 'post-6.md',
       tags: [ 'F', 'G' ] } ] }